-- Per-user Google Analytics OAuth connections.
--
-- These credentials let an authenticated user connect their own GA4 account,
-- list accessible GA4 properties, and run dashboard reports with the same
-- mt_link_id filters generated by project tracking links.

create table if not exists public.user_google_analytics_connections (
  user_id uuid primary key references auth.users(id) on delete cascade,
  account_email text,
  access_token text not null,
  refresh_token text,
  token_expires_at timestamptz not null,
  scope text,
  connected_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger user_google_analytics_connections_touch_updated_at
  before update on public.user_google_analytics_connections
  for each row execute function public.touch_updated_at();

alter table public.user_google_analytics_connections enable row level security;

create policy "users read own google analytics connection"
  on public.user_google_analytics_connections
  for select to authenticated
  using (user_id = auth.uid());

create policy "users create own google analytics connection"
  on public.user_google_analytics_connections
  for insert to authenticated
  with check (user_id = auth.uid());

create policy "users update own google analytics connection"
  on public.user_google_analytics_connections
  for update to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

create policy "users delete own google analytics connection"
  on public.user_google_analytics_connections
  for delete to authenticated
  using (user_id = auth.uid());
